# Example 5
# ubuntu/focal64
# Separate Web and database servers serving up static/dynamic sites via Puppet.

nodes = [
  { :hostname => 'lat5web', :ip => '192.168.0.42', :box => 'ubuntu/focal64' },
  { :hostname => 'lat5db',  :ip => '192.168.0.43', :box => 'ubuntu/focal64', :ram => 512 }
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = "ubuntu/focal64"
      nodeconfig.vm.hostname = node[:hostname] + ".box"
      nodeconfig.vm.network "private_network", ip: node[:ip]

      memory = node[:ram] ? node[:ram] : 256;
      nodeconfig.vm.provider :virtualbox do |vb|
        vb.customize [
          "modifyvm", :id,
          "--cpuexecutioncap", "50",
          "--memory", memory.to_s,
        ]
      end
    end
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file = "site.pp"
    puppet.module_path = "puppet/modules"
  end
end
